<?php

namespace App\Jobs;

use App\Models\Pulse;
use App\Notifications\CommentNotification;
use App\Services\GroqService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;

class AiAnswerPulseJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable;

    private Pulse $pulse;

    public function __construct(Pulse $pulse)
    {
        $this->pulse = $pulse;
    }

    public function handle(): void
    {
        $groqService = new GroqService();
        $prompt  = $this->pulse->code ? "{$this->pulse->text}\\n\\n\\n{$this->pulse->code['sourceCode']}" : $this->pulse->text;
        $response = $groqService->queryGroq($prompt);

        if(!$response) {
            return;
        }

        $message = '>This comment was automatically generated by our A.I. to address your issue promptly. Please note that it is a one-time response and will not handle additional replies.';
        $text = "{$message}\n\n{$response}";

        $comment = $this->pulse->comments()->create([
            'user_id' => 3,
            'text' => $text,
        ]);

        $this->pulse->user->notify(new CommentNotification($comment,isAiGenerated: true));
    }
}
